# Tensor

In [18]:
import torch
import numpy as np
torch.manual_seed(42)

In [27]:
# broadcasting
a  = torch.rand(3,3)
scaler = 5
print(a)
print(a+scaler)

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]])
tensor([[5.9516, 5.0753, 5.8860],
        [5.5832, 5.3376, 5.8090],
        [5.5779, 5.9040, 5.5547]])


In [29]:
# (3,3) + (1,3)
b = torch.rand(1,3)
print(a, b)
print(a+b)

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]]) tensor([[0.7104, 0.9464, 0.7890]])
tensor([[1.6620, 1.0217, 1.6750],
        [1.2936, 1.2841, 1.5980],
        [1.2884, 1.8504, 1.3437]])


In [30]:
x=torch.ones(2,2, requires_grad=True)
y = x+2
z = y * y *3
out = z.mean()
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [49]:
x = torch.tensor(2., requires_grad=True)
y = torch.tensor(3., requires_grad=True)
z = y * torch.log(x)  + torch.sin(y)
z.backward()
print(x.grad, y.grad)

tensor(1.5000) tensor(-0.2968)


In [44]:
x = torch.tensor([2.], requires_grad=True)
x.detach().numpy()

array([2.], dtype=float32)

In [59]:
x = torch.tensor(2., requires_grad=True)
y = torch.tensor(3., requires_grad=True)
c = x + y
c.retain_grad()
z = c ** 2
z.backward()
print(x.grad, y.grad)
print(c.grad)

tensor(10.) tensor(10.)
tensor(10.)
